### ISSUE TITLE
App authorized... nothing happens.

### ISSUE THREAD

**Issue by mkody** [jumono/QuickTweet#2]
<sup>FIRST ISSUE, WOO!</sup>
So, I've tried to run QuickTweet on my Windows machine _(WinXP 32bits, good stuff y'know)_.
It opens, I open it, click that (+) button, login and authorize and... that's it. I'm left with a blank window and nothing's happening.
![lh98k](https://cloud.githubusercontent.com/assets/843787/16729922/f519c8c0-476f-11e6-9cf6-5ceb45cc2eef.png)

Also, restarting the app and clicking the (+) button keeps me logged in, which is kind of bad if I wanted to use a second account for example.

**Comment by jumono** [comment]
This might be an issue with writing the accounts.json file, I will have to take a look at that someday.
